# 🌱 Stage 1: NumPy Foundations

## 🎯 Objective
Learn array structure, shape, indexing, and basic operations

---

## Table of Contents
1. What is NumPy? Why Use It?
2. Creating Arrays
3. Array Attributes
4. Indexing & Slicing
5. Reshaping & Flattening
6. Practice Exercises

---

## 1. What is NumPy? Why Use It?

### 📚 Theory

**NumPy (Numerical Python)** is the fundamental package for scientific computing in Python.

### Key Benefits:
- **Speed**: 10-100x faster than Python lists
- **Vectorization**: Perform operations on entire arrays at once
- **Memory Efficient**: Fixed data types save memory
- **Foundation**: Used by pandas, scikit-learn, TensorFlow, etc.

### Arrays vs Lists 🥊

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Speed | Slow | Fast (10-100x) |
| Data Type | Mixed types | Fixed type |
| Operations | Element-wise loops | Vectorized |
| Memory | More | Less |
| Functionality | Basic | Math operations |


In [1]:
# Import NumPy
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.5


In [2]:
# Speed comparison: List vs NumPy Array
import time

# Using Python List
python_list = list(range(1000000))
start = time.time()
result_list = [x * 2 for x in python_list]
list_time = time.time() - start

# Using NumPy Array
numpy_array = np.arange(1000000)
start = time.time()
result_array = numpy_array * 2
numpy_time = time.time() - start

print(f"List time: {list_time:.5f} seconds")
print(f"NumPy time: {numpy_time:.5f} seconds")
print(f"NumPy is {list_time/numpy_time:.1f}x faster!")

List time: 0.05860 seconds
NumPy time: 0.00283 seconds
NumPy is 20.7x faster!


---

## 2. Creating Arrays

### 📚 Theory

NumPy provides multiple ways to create arrays:

1. **From Python Lists**: `np.array()`
2. **Zeros**: `np.zeros()` - Create array filled with 0
3. **Ones**: `np.ones()` - Create array filled with 1
4. **Full**: `np.full()` - Create array filled with specific value
5. **Range**: `np.arange()` - Like Python's range()
6. **Linspace**: `np.linspace()` - Evenly spaced numbers
7. **Identity**: `np.eye()` - Identity matrix (diagonal 1s)


In [3]:
# 1. From Python List
arr_from_list = np.array([1, 2, 3, 4, 5])
print("From list:", arr_from_list)

# 2D array from nested list
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:\n", arr_2d)

From list: [1 2 3 4 5]

2D array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# 2. Zeros - Create array filled with zeros
zeros_1d = np.zeros(5)  # 1D array with 5 zeros
print("1D zeros:", zeros_1d)

zeros_2d = np.zeros((2, 3))  # 2x3 array of zeros
print("\n2D zeros:\n", zeros_2d)

zeros_3d = np.zeros((2, 3, 4))  # 3D array
print("\n3D zeros shape:", zeros_3d.shape)

1D zeros: [0. 0. 0. 0. 0.]

2D zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

3D zeros shape: (2, 3, 4)


In [7]:
# 3. Ones - Create array filled with ones
ones_1d = np.ones(4)
print("1D ones:", ones_1d)

ones_2d = np.ones((3, 3))
print("\n2D ones:\n", ones_2d)

1D ones: [1. 1. 1. 1.]

2D ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 4. Full - Create array with specific value
full_array = np.full((2, 2), 7)  # 2x2 array filled with 7
print("Full array (7):\n", full_array)

full_array_2 = np.full((3, 4), 3.14)
print("\nFull array (3.14):\n", full_array_2)

Full array (7):
 [[7 7]
 [7 7]]

Full array (3.14):
 [[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


In [9]:
# 5. Arange - Like Python's range()
# np.arange(start, stop, step)

arange_1 = np.arange(10)  # 0 to 9
print("Arange(10):", arange_1)

arange_2 = np.arange(0, 10, 2)  # 0, 2, 4, 6, 8
print("Arange(0, 10, 2):", arange_2)

arange_3 = np.arange(5, 15)  # 5 to 14
print("Arange(5, 15):", arange_3)

Arange(10): [0 1 2 3 4 5 6 7 8 9]
Arange(0, 10, 2): [0 2 4 6 8]
Arange(5, 15): [ 5  6  7  8  9 10 11 12 13 14]


In [10]:
# 6. Linspace - Evenly spaced numbers
# np.linspace(start, stop, num_of_points)

linspace_1 = np.linspace(0, 1, 5)  # 5 points between 0 and 1
print("Linspace(0, 1, 5):", linspace_1)

linspace_2 = np.linspace(0, 10, 11)  # 11 points between 0 and 10
print("Linspace(0, 10, 11):", linspace_2)

# Difference: arange uses step, linspace uses number of points

Linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
Linspace(0, 10, 11): [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
# 7. Identity Matrix - Diagonal 1s, rest 0s
identity_3x3 = np.eye(3)
print("3x3 Identity Matrix:\n", identity_3x3)

identity_5x5 = np.eye(5)
print("\n5x5 Identity Matrix:\n", identity_5x5)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

## 3. Array Attributes (Metadata)

### 📚 Theory

Every NumPy array has important properties:

| Attribute | Description | Example Output |
|-----------|-------------|----------------|
| `shape` | Dimensions (rows, cols) | (2, 3) |
| `size` | Total number of elements | 6 |
| `dtype` | Data type | int64, float64 |
| `ndim` | Number of dimensions | 2 |
| `itemsize` | Bytes per element | 8 |


In [12]:
# Create a sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("\n" + "="*50)

# Shape - Dimensions of array
print(f"Shape: {arr.shape}")  # (2, 3) = 2 rows, 3 columns

# Size - Total number of elements
print(f"Size: {arr.size}")  # 6 elements

# Dtype - Data type
print(f"Data type: {arr.dtype}")  # int64 or int32

# Ndim - Number of dimensions
print(f"Number of dimensions: {arr.ndim}")  # 2D array

# Itemsize - Memory per element (in bytes)
print(f"Bytes per element: {arr.itemsize}")  # 8 bytes for int64

Array:
 [[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2
Bytes per element: 8


In [13]:
# Different dimensions examples

# 1D array
arr_1d = np.array([1, 2, 3, 4])
print("1D Array:", arr_1d)
print(f"Shape: {arr_1d.shape}, Ndim: {arr_1d.ndim}\n")

# 2D array
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("2D Array:\n", arr_2d)
print(f"Shape: {arr_2d.shape}, Ndim: {arr_2d.ndim}\n")

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr_3d)
print(f"Shape: {arr_3d.shape}, Ndim: {arr_3d.ndim}")

1D Array: [1 2 3 4]
Shape: (4,), Ndim: 1

2D Array:
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2), Ndim: 2

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2), Ndim: 3


In [14]:
# Data types

# Integer array
int_arr = np.array([1, 2, 3])
print(f"Integer array dtype: {int_arr.dtype}")

# Float array
float_arr = np.array([1.5, 2.5, 3.5])
print(f"Float array dtype: {float_arr.dtype}")

# Explicitly specify dtype
explicit_arr = np.array([1, 2, 3], dtype=np.float64)
print(f"Explicit float64 array: {explicit_arr}")
print(f"Dtype: {explicit_arr.dtype}")

Integer array dtype: int64
Float array dtype: float64
Explicit float64 array: [1. 2. 3.]
Dtype: float64


---

## 4. Indexing & Slicing

### 📚 Theory

**Indexing**: Access individual elements
**Slicing**: Access subsets of arrays

### Syntax:
- **1D**: `arr[index]`
- **2D**: `arr[row, column]`
- **Slicing**: `arr[start:stop:step]`
- **Negative indexing**: `-1` is last element


In [15]:
# 1D Array Indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print("Array:", arr_1d)

print(f"First element: {arr_1d[0]}")  # 10
print(f"Third element: {arr_1d[2]}")  # 30
print(f"Last element: {arr_1d[-1]}")  # 50
print(f"Second last: {arr_1d[-2]}")  # 40

Array: [10 20 30 40 50]
First element: 10
Third element: 30
Last element: 50
Second last: 40


In [16]:
# 1D Array Slicing
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)

print(f"First 5 elements: {arr[:5]}")  # [0, 1, 2, 3, 4]
print(f"Last 3 elements: {arr[-3:]}")  # [7, 8, 9]
print(f"Middle elements (index 3-6): {arr[3:7]}")  # [3, 4, 5, 6]
print(f"Every 2nd element: {arr[::2]}")  # [0, 2, 4, 6, 8]
print(f"Reverse array: {arr[::-1]}")  # [9, 8, 7, ..., 0]

Original array: [0 1 2 3 4 5 6 7 8 9]
First 5 elements: [0 1 2 3 4]
Last 3 elements: [7 8 9]
Middle elements (index 3-6): [3 4 5 6]
Every 2nd element: [0 2 4 6 8]
Reverse array: [9 8 7 6 5 4 3 2 1 0]


In [17]:
# 2D Array Indexing
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("2D Array:\n", arr_2d)
print()

# Access individual elements: arr[row, column]
print(f"Element at [0, 1]: {arr_2d[0, 1]}")  # 2
print(f"Element at [1, 2]: {arr_2d[1, 2]}")  # 6
print(f"Element at [2, 0]: {arr_2d[2, 0]}")  # 7

# Access entire row
print(f"First row: {arr_2d[0]}")  # [1, 2, 3]
print(f"Last row: {arr_2d[-1]}")  # [7, 8, 9]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at [0, 1]: 2
Element at [1, 2]: 6
Element at [2, 0]: 7
First row: [1 2 3]
Last row: [7 8 9]


In [18]:
# 2D Array Slicing
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("Original 2D Array:\n", arr_2d)
print()

# Extract column (all rows, specific column)
print("Second column (index 1):", arr_2d[:, 1])  # [2, 6, 10]

# Extract row range
print("\nFirst 2 rows:\n", arr_2d[:2, :])  # [[1,2,3,4], [5,6,7,8]]

# Extract sub-matrix
print("\nSub-matrix (rows 1-2, cols 2-3):\n", arr_2d[1:, 2:])
# [[7, 8], [11, 12]]

# Extract specific rows and columns
print("\nFirst 2 rows, last 2 columns:\n", arr_2d[:2, -2:])
# [[3, 4], [7, 8]]

Original 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Second column (index 1): [ 2  6 10]

First 2 rows:
 [[1 2 3 4]
 [5 6 7 8]]

Sub-matrix (rows 1-2, cols 2-3):
 [[ 7  8]
 [11 12]]

First 2 rows, last 2 columns:
 [[3 4]
 [7 8]]


In [19]:
# Boolean Indexing (Masking)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array:", arr)

# Create boolean mask
mask = arr > 5
print(f"\nMask (arr > 5): {mask}")

# Apply mask to filter
filtered = arr[arr > 5]
print(f"Elements > 5: {filtered}")  # [6, 7, 8, 9, 10]

# Multiple conditions
filtered_2 = arr[(arr > 3) & (arr < 8)]
print(f"Elements between 3 and 8: {filtered_2}")  # [4, 5, 6, 7]

Array: [ 1  2  3  4  5  6  7  8  9 10]

Mask (arr > 5): [False False False False False  True  True  True  True  True]
Elements > 5: [ 6  7  8  9 10]
Elements between 3 and 8: [4 5 6 7]


In [20]:
# Fancy Indexing
arr = np.array([10, 20, 30, 40, 50, 60])
print("Array:", arr)

# Select specific indices
indices = [0, 2, 4]
print(f"Elements at indices {indices}: {arr[indices]}")  # [10, 30, 50]

# 2D Fancy Indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D Array:\n{arr_2d}")

# Select elements at [0,1] and [1,2]
print(f"Fancy indexing [[0,1], [1,2]]: {arr_2d[[0, 1], [1, 2]]}")  # [2, 6]

Array: [10 20 30 40 50 60]
Elements at indices [0, 2, 4]: [10 30 50]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Fancy indexing [[0,1], [1,2]]: [2 6]


---

## 5. Reshaping & Flattening

### 📚 Theory

| Method | Description | Returns | Use Case |
|--------|-------------|---------|----------|
| `reshape()` | Change shape | New view | ML input formatting |
| `flatten()` | To 1D | Copy | When you need a copy |
| `ravel()` | To 1D | View (faster) | Memory efficient |
| `.T` | Transpose | View | Swap rows/columns |
| `np.newaxis` | Add dimension | View | Broadcasting |
| `squeeze()` | Remove 1-dims | View | Clean dimensions |
| `expand_dims()` | Add dimension | View | Shape matching |


In [21]:
# Reshape - Change array shape
arr = np.arange(12)
print("Original array:", arr)
print(f"Shape: {arr.shape}\n")

# Reshape to 3x4
reshaped_3x4 = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_3x4)

# Reshape to 2x6
reshaped_2x6 = arr.reshape(2, 6)
print("\nReshaped to 2x6:\n", reshaped_2x6)

# Reshape to 3D
reshaped_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 2x2x3:\n", reshaped_3d)
print(f"Shape: {reshaped_3d.shape}")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape: (2, 2, 3)


In [22]:
# Auto-calculate dimension with -1
arr = np.arange(24)

# NumPy calculates the missing dimension
auto_reshape = arr.reshape(4, -1)  # Becomes 4x6
print("Reshape(4, -1):\n", auto_reshape)
print(f"Shape: {auto_reshape.shape}\n")

auto_reshape_2 = arr.reshape(-1, 8)  # Becomes 3x8
print("Reshape(-1, 8):\n", auto_reshape_2)
print(f"Shape: {auto_reshape_2.shape}")

Reshape(4, -1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape: (4, 6)

Reshape(-1, 8):
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
Shape: (3, 8)


In [23]:
# Flatten vs Ravel
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)
print()

# Flatten - Returns a COPY
flattened = arr_2d.flatten()
print("Flattened (copy):", flattened)
flattened[0] = 999  # Modify flattened
print("After modifying flattened[0]:")
print("Original array:\n", arr_2d)  # Unchanged!
print()

# Ravel - Returns a VIEW (faster, memory efficient)
raveled = arr_2d.ravel()
print("Raveled (view):", raveled)
raveled[0] = 888  # Modify raveled
print("After modifying raveled[0]:")
print("Original array:\n", arr_2d)  # Changed!

2D Array:
 [[1 2 3]
 [4 5 6]]

Flattened (copy): [1 2 3 4 5 6]
After modifying flattened[0]:
Original array:
 [[1 2 3]
 [4 5 6]]

Raveled (view): [1 2 3 4 5 6]
After modifying raveled[0]:
Original array:
 [[888   2   3]
 [  4   5   6]]


In [24]:
# Transpose - Swap rows and columns
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original (2x3):\n", arr)
print(f"Shape: {arr.shape}\n")

# Transpose using .T
transposed = arr.T
print("Transposed (3x2):\n", transposed)
print(f"Shape: {transposed.shape}")

Original (2x3):
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed (3x2):
 [[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [25]:
# Adding dimensions with np.newaxis
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)
print(f"Shape: {arr.shape}\n")

# Add row dimension (convert to column vector)
col_vector = arr[:, np.newaxis]
print("Column vector:\n", col_vector)
print(f"Shape: {col_vector.shape}\n")

# Add column dimension (convert to row vector)
row_vector = arr[np.newaxis, :]
print("Row vector:\n", row_vector)
print(f"Shape: {row_vector.shape}")

Original array: [1 2 3 4]
Shape: (4,)

Column vector:
 [[1]
 [2]
 [3]
 [4]]
Shape: (4, 1)

Row vector:
 [[1 2 3 4]]
Shape: (1, 4)


In [26]:
# Squeeze - Remove single-dimensional entries
arr = np.array([[[1, 2, 3]]])
print("Original shape:", arr.shape)  # (1, 1, 3)

squeezed = np.squeeze(arr)
print("After squeeze:", squeezed)
print("Squeezed shape:", squeezed.shape)  # (3,)

Original shape: (1, 1, 3)
After squeeze: [1 2 3]
Squeezed shape: (3,)


In [27]:
# Expand dims - Add dimension at specified position
arr = np.array([1, 2, 3])
print("Original:", arr)
print(f"Shape: {arr.shape}\n")

# Add dimension at axis 0
expanded_0 = np.expand_dims(arr, axis=0)
print("Expanded at axis 0:", expanded_0)
print(f"Shape: {expanded_0.shape}\n")

# Add dimension at axis 1
expanded_1 = np.expand_dims(arr, axis=1)
print("Expanded at axis 1:\n", expanded_1)
print(f"Shape: {expanded_1.shape}")

Original: [1 2 3]
Shape: (3,)

Expanded at axis 0: [[1 2 3]]
Shape: (1, 3)

Expanded at axis 1:
 [[1]
 [2]
 [3]]
Shape: (3, 1)


---

## 6. 🧪 Practice Exercises

### Exercise 1: Create a 3x3 array
Create a 3x3 array using `np.arange()` and reshape it

In [28]:
# Your code here
exercise_1 = np.arange(9).reshape(3, 3)
print("3x3 Array:\n", exercise_1)

3x3 Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


### Exercise 2: Extract middle column and last row

In [29]:
# Using the array from Exercise 1
middle_column = exercise_1[:, 1]
last_row = exercise_1[-1, :]

print("Middle column:", middle_column)
print("Last row:", last_row)

Middle column: [1 4 7]
Last row: [6 7 8]


### Exercise 3: Flatten the matrix

In [30]:
# Flatten the 3x3 array
flattened_matrix = exercise_1.flatten()
print("Flattened matrix:", flattened_matrix)

Flattened matrix: [0 1 2 3 4 5 6 7 8]


### Exercise 4: Create and manipulate arrays
1. Create a 10-element array from 0 to 9
2. Extract even numbers
3. Reshape to 2x5

In [31]:
# Step 1: Create array
arr = np.arange(10)
print("Original:", arr)

# Step 2: Extract even numbers
even_numbers = arr[arr % 2 == 0]
print("Even numbers:", even_numbers)

# Step 3: Reshape
reshaped = arr.reshape(2, 5)
print("Reshaped to 2x5:\n", reshaped)

Original: [0 1 2 3 4 5 6 7 8 9]
Even numbers: [0 2 4 6 8]
Reshaped to 2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


---

## 📝 Key Takeaways

1. ✅ NumPy arrays are 10-100x faster than Python lists
2. ✅ Multiple ways to create arrays: `array()`, `zeros()`, `ones()`, `arange()`, `linspace()`, `eye()`
3. ✅ Important attributes: `shape`, `size`, `dtype`, `ndim`, `itemsize`
4. ✅ Indexing: `arr[row, col]`, slicing: `arr[start:stop:step]`
5. ✅ Boolean indexing: `arr[arr > 5]`
6. ✅ Reshaping: `reshape()`, `flatten()`, `ravel()`, `.T`
7. ✅ Use `ravel()` instead of `flatten()` for better performance (returns view)

---