# ⚙️ Stage 2: Data Manipulation

## 🎯 Objective
Learn calculations, filtering, sorting, and random operations on NumPy arrays

---

## Table of Contents
1. Mathematical & Statistical Operations
2. Conditional Filtering & Boolean Logic
3. Sorting & Searching
4. Random Module
5. Set Operations
6. Practice Exercises

In [2]:
import numpy as np

---

## 1. Mathematical & Statistical Operations

### 📚 Theory

NumPy provides fast vectorized operations:

#### Element-wise Operations:
- Addition: `+` or `np.add()`
- Subtraction: `-` or `np.subtract()`
- Multiplication: `*` or `np.multiply()`
- Division: `/` or `np.divide()`
- Power: `**` or `np.power()`

#### Aggregation Functions:
- `np.sum()` - Sum of elements
- `np.mean()` - Average
- `np.std()` - Standard deviation
- `np.var()` - Variance
- `np.min()`, `np.max()` - Min/Max
- `np.argmin()`, `np.argmax()` - Index of min/max

### ✅ Daily Use:
- Normalization
- Summary statistics
- Data scaling
- Feature engineering

### Element-wise Operations

In [3]:
# Create sample array
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
print()

# Addition
print("Add 10:", arr + 10)
print("np.add(arr, 10):", np.add(arr, 10))
print()

# Multiplication
print("Multiply by 2:", arr * 2)
print("np.multiply(arr, 2):", np.multiply(arr, 2))
print()

# Power
print("Square (arr ** 2):", arr ** 2)
print("np.power(arr, 2):", np.power(arr, 2))
print()

# Square root
print("Square root:", np.sqrt(arr))

Original array: [1 2 3 4 5]

Add 10: [11 12 13 14 15]
np.add(arr, 10): [11 12 13 14 15]

Multiply by 2: [ 2  4  6  8 10]
np.multiply(arr, 2): [ 2  4  6  8 10]

Square (arr ** 2): [ 1  4  9 16 25]
np.power(arr, 2): [ 1  4  9 16 25]

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]


In [4]:
# Operations between two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print("Array 1:", arr1)
print("Array 2:", arr2)
print()

print("Addition:", arr1 + arr2)
print("Subtraction:", arr2 - arr1)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


### Statistical Functions

In [ ]:
# Salary data example
salaries = np.array([25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000])
print("Salaries:", salaries)
print()

# Calculate statistics
print(f"Sum: ${np.sum(salaries):,}")
print(f"Mean (Average): ${np.mean(salaries):,.2f}")
print(f"Median: ${np.median(salaries):,}")
print(f"Standard Deviation: ${np.std(salaries):,.2f}")
print(f"Variance: {np.var(salaries):,.2f}")
print(f"Minimum: ${np.min(salaries):,}")
print(f"Maximum: ${np.max(salaries):,}")

In [5]:
# Argmin and Argmax - Find index of min/max
arr = np.array([50, 30, 80, 20, 90, 10])
print("Array:", arr)
print()

min_idx = np.argmin(arr)
max_idx = np.argmax(arr)

print(f"Index of minimum value: {min_idx}")
print(f"Minimum value: {arr[min_idx]}")
print()
print(f"Index of maximum value: {max_idx}")
print(f"Maximum value: {arr[max_idx]}")

Array: [50 30 80 20 90 10]

Index of minimum value: 5
Minimum value: 10

Index of maximum value: 4
Maximum value: 90


### Operations on 2D Arrays (with axis)

In [6]:
# Create 2D array (3 students, 4 subjects)
scores = np.array([[85, 90, 78, 92],  # Student 1
                   [88, 76, 95, 89],  # Student 2
                   [92, 88, 91, 87]]) # Student 3

print("Scores (3 students × 4 subjects):\n", scores)
print()

# axis=0: operate along rows (for each column/subject)
print("Average per subject (axis=0):", np.mean(scores, axis=0))
print()

# axis=1: operate along columns (for each row/student)
print("Average per student (axis=1):", np.mean(scores, axis=1))
print()

# Overall statistics
print(f"Overall average: {np.mean(scores):.2f}")
print(f"Overall max: {np.max(scores)}")
print(f"Overall min: {np.min(scores)}")

Scores (3 students × 4 subjects):
 [[85 90 78 92]
 [88 76 95 89]
 [92 88 91 87]]

Average per subject (axis=0): [88.33333333 84.66666667 88.         89.33333333]

Average per student (axis=1): [86.25 87.   89.5 ]

Overall average: 87.58
Overall max: 95
Overall min: 76


### Cumulative Operations

In [7]:
# Cumulative sum and product
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print()

# Cumulative sum: [1, 1+2, 1+2+3, ...]
cum_sum = np.cumsum(arr)
print("Cumulative sum:", cum_sum)

# Cumulative product: [1, 1*2, 1*2*3, ...]
cum_prod = np.cumprod(arr)
print("Cumulative product:", cum_prod)

Array: [1 2 3 4 5]

Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]


---

## 2. Conditional Filtering & Boolean Logic

### 📚 Theory

**Boolean Indexing** allows filtering data based on conditions.

#### Comparison Operators:
- `>`, `<`, `>=`, `<=`, `==`, `!=`

#### Logical Operators:
- `&` - AND
- `|` - OR
- `~` - NOT

#### Special Functions:
- `np.where()` - Conditional replacement

### ✅ Daily Use:
- Filtering outliers
- Data cleaning
- Conditional operations
- Decision making

In [8]:
# Simple filtering
arr = np.array([5, 12, 8, 20, 3, 15, 9, 25])
print("Array:", arr)
print()

# Filter values > 10
filtered = arr[arr > 10]
print("Values > 10:", filtered)

# Filter values <= 10
filtered_2 = arr[arr <= 10]
print("Values <= 10:", filtered_2)

# Filter even numbers
even = arr[arr % 2 == 0]
print("Even numbers:", even)

Array: [ 5 12  8 20  3 15  9 25]

Values > 10: [12 20 15 25]
Values <= 10: [5 8 3 9]
Even numbers: [12  8 20]


In [9]:
# Multiple conditions with & (AND) and | (OR)
salaries = np.array([25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000])
print("Salaries:", salaries)
print()

# Find salaries between 30K and 50K (inclusive)
mid_range = salaries[(salaries >= 30000) & (salaries <= 50000)]
print("Salaries between 30K-50K:", mid_range)

# Find salaries < 30K OR > 55K
extremes = salaries[(salaries < 30000) | (salaries > 55000)]
print("Salaries < 30K or > 55K:", extremes)

# NOT operator (~)
not_mid_range = salaries[~((salaries >= 30000) & (salaries <= 50000))]
print("NOT in 30K-50K range:", not_mid_range)

Salaries: [25000 30000 35000 40000 45000 50000 55000 60000]

Salaries between 30K-50K: [30000 35000 40000 45000 50000]
Salaries < 30K or > 55K: [25000 60000]
NOT in 30K-50K range: [25000 55000 60000]


In [10]:
# np.where() - Conditional replacement
# Syntax: np.where(condition, value_if_true, value_if_false)

salaries = np.array([25000, 30000, 35000, 40000, 45000, 50000])
print("Original salaries:", salaries)
print()

# Replace salaries < 35000 with 35000, keep others as is
adjusted = np.where(salaries < 35000, 35000, salaries)
print("After adjustment (min 35K):", adjusted)
print()

# Create labels: 'Low' if < 35K, 'High' otherwise
labels = np.where(salaries < 35000, 'Low', 'High')
print("Salary labels:", labels)

Original salaries: [25000 30000 35000 40000 45000 50000]

After adjustment (min 35K): [35000 35000 35000 40000 45000 50000]

Salary labels: ['Low' 'Low' 'High' 'High' 'High' 'High']


In [11]:
# Practical example: Replace negative values with 0
data = np.array([10, -5, 20, -3, 15, -8, 25])
print("Original data:", data)

# Replace negatives with 0
cleaned = np.where(data < 0, 0, data)
print("After replacing negatives with 0:", cleaned)

Original data: [10 -5 20 -3 15 -8 25]
After replacing negatives with 0: [10  0 20  0 15  0 25]


---

## 3. Sorting & Searching

### 📚 Theory

| Function | Description | Returns |
|----------|-------------|----------|
| `np.sort()` | Sort array | Sorted array |
| `np.argsort()` | Sort indices | Indices |
| `np.unique()` | Unique values | Unique array |
| `np.in1d()` | Check membership | Boolean array |

### ✅ Daily Use:
- Ranking
- Finding duplicates
- Data validation
- Top-K selection

In [12]:
# Basic sorting
arr = np.array([64, 34, 25, 12, 22, 11, 90])
print("Original:", arr)

# Sort in ascending order
sorted_arr = np.sort(arr)
print("Sorted (ascending):", sorted_arr)

# Sort in descending order
sorted_desc = np.sort(arr)[::-1]
print("Sorted (descending):", sorted_desc)

# Note: np.sort() doesn't modify original
print("Original (unchanged):", arr)

Original: [64 34 25 12 22 11 90]
Sorted (ascending): [11 12 22 25 34 64 90]
Sorted (descending): [90 64 34 25 22 12 11]
Original (unchanged): [64 34 25 12 22 11 90]


In [13]:
# Sorting 2D arrays
arr_2d = np.array([[3, 2, 1],
                   [6, 5, 4],
                   [9, 8, 7]])

print("Original 2D array:\n", arr_2d)
print()

# Sort each row
sorted_rows = np.sort(arr_2d, axis=1)
print("Sorted by rows (axis=1):\n", sorted_rows)
print()

# Sort each column
sorted_cols = np.sort(arr_2d, axis=0)
print("Sorted by columns (axis=0):\n", sorted_cols)

Original 2D array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Sorted by rows (axis=1):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sorted by columns (axis=0):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [14]:
# Argsort - Get sorting indices
scores = np.array([85, 92, 78, 95, 88])
names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])

print("Scores:", scores)
print("Names:", names)
print()

# Get indices that would sort the scores
sorted_indices = np.argsort(scores)
print("Sorted indices (ascending):", sorted_indices)
print("Sorted scores:", scores[sorted_indices])
print("Sorted names:", names[sorted_indices])
print()

# Descending order (reverse the indices)
desc_indices = np.argsort(scores)[::-1]
print("Top scorers:")
for i in desc_indices:
    print(f"  {names[i]}: {scores[i]}")

Scores: [85 92 78 95 88]
Names: ['Alice' 'Bob' 'Charlie' 'David' 'Eve']

Sorted indices (ascending): [2 0 4 1 3]
Sorted scores: [78 85 88 92 95]
Sorted names: ['Charlie' 'Alice' 'Eve' 'Bob' 'David']

Top scorers:
  David: 95
  Bob: 92
  Eve: 88
  Alice: 85
  Charlie: 78


In [15]:
# Unique values
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])
print("Array with duplicates:", arr)
print()

# Get unique values
unique_vals = np.unique(arr)
print("Unique values:", unique_vals)

# Get unique values with counts
unique_vals, counts = np.unique(arr, return_counts=True)
print("\nValue frequency:")
for val, count in zip(unique_vals, counts):
    print(f"  {val}: appears {count} times")

Array with duplicates: [1 2 2 3 3 3 4 4 4 4 5]

Unique values: [1 2 3 4 5]

Value frequency:
  1: appears 1 times
  2: appears 2 times
  3: appears 3 times
  4: appears 4 times
  5: appears 1 times


In [21]:
# Check membership with in1d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
check_vals = [2, 5, 11, 15]

print("Array:", arr)
print("Checking values:", check_vals)
print()

# Check which values are in arr
is_in = np.isin(check_vals, arr)
print("Is in array:", is_in)

for val, found in zip(check_vals, is_in):
    print(f"  {val}: {'Found' if found else 'Not found'}")

Array: [ 1  2  3  4  5  6  7  8  9 10]
Checking values: [2, 5, 11, 15]

Is in array: [ True  True False False]
  2: Found
  5: Found
  11: Not found
  15: Not found


---

## 4. Random Module

### 📚 Theory

NumPy's random module generates random numbers for:

| Function | Description | Range/Distribution |
|----------|-------------|-------------------|
| `rand()` | Uniform [0, 1) | 0 to 1 |
| `randn()` | Normal distribution | Mean=0, Std=1 |
| `randint()` | Random integers | Specified range |
| `choice()` | Random selection | From array |
| `shuffle()` | Shuffle in-place | Randomize order |
| `seed()` | Set random seed | Reproducibility |

### ✅ Daily Use:
- Train-test split
- Simulations
- Data augmentation
- Initialization

In [22]:
# Set seed for reproducibility
np.random.seed(42)
print("Seed set to 42 for reproducible results\n")

# Random floats between 0 and 1
rand_floats = np.random.rand(5)
print("5 random floats [0, 1):", rand_floats)
print()

# Random floats in 2D
rand_2d = np.random.rand(3, 4)
print("3x4 random array:\n", rand_2d)

Seed set to 42 for reproducible results

5 random floats [0, 1): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

3x4 random array:
 [[0.15599452 0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451 0.30424224]]


In [23]:
# Normal distribution (mean=0, std=1)
normal_dist = np.random.randn(1000)
print("1000 samples from normal distribution:")
print(f"Mean: {np.mean(normal_dist):.4f} (should be ~0)")
print(f"Std: {np.std(normal_dist):.4f} (should be ~1)")
print(f"Sample values: {normal_dist[:10]}")

1000 samples from normal distribution:
Mean: 0.0267 (should be ~0)
Std: 1.0005 (should be ~1)
Sample values: [-2.61254901  0.95036968  0.81644508 -1.523876   -0.42804606 -0.74240684
 -0.7033438  -2.13962066 -0.62947496  0.59772047]


In [24]:
# Random integers
# randint(low, high, size)

# Simulate dice rolls (1-6)
dice_rolls = np.random.randint(1, 7, size=10)
print("10 dice rolls:", dice_rolls)
print()

# Random 2D array of integers
rand_ints = np.random.randint(1, 100, size=(3, 3))
print("3x3 random integers (1-99):\n", rand_ints)

10 dice rolls: [3 4 2 6 2 3 6 5 1 3]

3x3 random integers (1-99):
 [[ 3 28 74]
 [35 61 93]
 [54 63 79]]


In [25]:
# Random choice - select from array
fruits = np.array(['Apple', 'Banana', 'Orange', 'Mango', 'Grape'])

# Pick one random fruit
random_fruit = np.random.choice(fruits)
print("Random fruit:", random_fruit)
print()

# Pick 3 random fruits (with replacement)
random_3 = np.random.choice(fruits, size=3)
print("3 random fruits:", random_3)
print()

# Pick 3 random fruits (without replacement - no duplicates)
random_3_unique = np.random.choice(fruits, size=3, replace=False)
print("3 unique random fruits:", random_3_unique)

Random fruit: Apple

3 random fruits: ['Mango' 'Apple' 'Grape']

3 unique random fruits: ['Orange' 'Grape' 'Mango']


In [27]:
# Shuffle array in-place
arr = np.arange(10)
print("Original:", arr)

np.random.shuffle(arr)
print("After shuffle:", arr)

Original: [0 1 2 3 4 5 6 7 8 9]
After shuffle: [5 6 1 9 0 8 2 7 3 4]


In [26]:
# Practical: Simulate coin flips
# 0 = Heads, 1 = Tails
coin_flips = np.random.randint(0, 2, size=100)

heads = np.sum(coin_flips == 0)
tails = np.sum(coin_flips == 1)

print(f"100 coin flips:")
print(f"Heads: {heads}")
print(f"Tails: {tails}")
print(f"First 20 flips: {coin_flips[:20]}")

100 coin flips:
Heads: 44
Tails: 56
First 20 flips: [1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 1 0 1]


In [28]:
# Practical: Simulate student marks (normal distribution)
# Mean = 75, Std = 10
marks = np.random.normal(loc=75, scale=10, size=100)

# Clip to 0-100 range
marks = np.clip(marks, 0, 100)

print("Student marks statistics:")
print(f"Mean: {np.mean(marks):.2f}")
print(f"Std: {np.std(marks):.2f}")
print(f"Min: {np.min(marks):.2f}")
print(f"Max: {np.max(marks):.2f}")
print(f"\nSample marks: {marks[:10].round(2)}")

Student marks statistics:
Mean: 75.68
Std: 10.68
Min: 50.45
Max: 100.00

Sample marks: [89.05 58.94 80.04 53.46 82.07 84.7  85.95 73.39 90.84 98.08]


---

## 5. Set Operations

### 📚 Theory

| Function | Description | Math Symbol |
|----------|-------------|-------------|
| `np.intersect1d()` | Common elements | A ∩ B |
| `np.union1d()` | All unique elements | A ∪ B |
| `np.setdiff1d()` | Elements in A not in B | A - B |
| `np.setxor1d()` | Elements in A or B, not both | A Δ B |

### ✅ Daily Use:
- Column comparisons
- Finding common/unique values
- Data validation

In [29]:
# Set operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

print("Array 1:", arr1)
print("Array 2:", arr2)
print()

# Intersection - common elements
intersection = np.intersect1d(arr1, arr2)
print("Intersection (common):", intersection)

# Union - all unique elements
union = np.union1d(arr1, arr2)
print("Union (all unique):", union)

# Difference - elements in arr1 not in arr2
diff = np.setdiff1d(arr1, arr2)
print("Difference (in arr1, not in arr2):", diff)

# Symmetric difference - elements in either, but not both
sym_diff = np.setxor1d(arr1, arr2)
print("Symmetric difference:", sym_diff)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]

Intersection (common): [4 5]
Union (all unique): [1 2 3 4 5 6 7 8]
Difference (in arr1, not in arr2): [1 2 3]
Symmetric difference: [1 2 3 6 7 8]


---

## 6. 🧪 Practice Exercises

### Exercise 1: Salary Statistics

In [30]:
# Create a salary array and calculate statistics
salaries = np.array([28000, 32000, 35000, 45000, 50000, 55000, 60000, 75000])

print("Salaries:", salaries)
print()

# Calculate average, max, and standard deviation
avg = np.mean(salaries)
max_sal = np.max(salaries)
std = np.std(salaries)

print(f"Average: ${avg:,.2f}")
print(f"Maximum: ${max_sal:,}")
print(f"Std Dev: ${std:,.2f}")

Salaries: [28000 32000 35000 45000 50000 55000 60000 75000]

Average: $47,500.00
Maximum: $75,000
Std Dev: $14,823.97


### Exercise 2: Filter and Replace Salaries

In [31]:
# Replace salaries < 30K with 0
salaries = np.array([25000, 30000, 35000, 28000, 45000, 20000])
print("Original:", salaries)

replaced = np.where(salaries < 30000, 0, salaries)
print("After replacing < 30K with 0:", replaced)
print()

# Filter salaries > 50K
salaries_2 = np.array([25000, 55000, 60000, 45000, 70000, 35000])
print("Original:", salaries_2)
high_earners = salaries_2[salaries_2 > 50000]
print("Salaries > 50K:", high_earners)

Original: [25000 30000 35000 28000 45000 20000]
After replacing < 30K with 0: [    0 30000 35000     0 45000     0]

Original: [25000 55000 60000 45000 70000 35000]
Salaries > 50K: [55000 60000 70000]


### Exercise 3: Coin Flip Simulation

In [32]:
# Simulate 100 coin flips (0 = Head, 1 = Tail)
np.random.seed(42)
flips = np.random.randint(0, 2, size=100)

heads = np.sum(flips == 0)
tails = np.sum(flips == 1)

print(f"Results of 100 coin flips:")
print(f"Heads: {heads}")
print(f"Tails: {tails}")
print(f"\nFirst 20 flips: {flips[:20]}")

Results of 100 coin flips:
Heads: 44
Tails: 56

First 20 flips: [0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0]


### Exercise 4: Student Marks Simulation

In [33]:
# Simulate marks of 100 students using normal distribution
# Mean = 70, Std = 15
np.random.seed(42)
marks = np.random.normal(loc=70, scale=15, size=100)

# Clip to valid range [0, 100]
marks = np.clip(marks, 0, 100)

print("Statistics for 100 students:")
print(f"Mean: {np.mean(marks):.2f}")
print(f"Std: {np.std(marks):.2f}")
print(f"Min: {np.min(marks):.2f}")
print(f"Max: {np.max(marks):.2f}")
print(f"Median: {np.median(marks):.2f}")
print()

# Count students by grade
grade_a = np.sum(marks >= 90)
grade_b = np.sum((marks >= 80) & (marks < 90))
grade_c = np.sum((marks >= 70) & (marks < 80))
grade_d = np.sum(marks < 70)

print("Grade distribution:")
print(f"A (90-100): {grade_a} students")
print(f"B (80-89): {grade_b} students")
print(f"C (70-79): {grade_c} students")
print(f"D (<70): {grade_d} students")

Statistics for 100 students:
Mean: 68.44
Std: 13.55
Min: 30.70
Max: 97.78
Median: 68.10

Grade distribution:
A (90-100): 8 students
B (80-89): 12 students
C (70-79): 26 students
D (<70): 54 students


---

## 📝 Key Takeaways

### Mathematical Operations:
1. ✅ Element-wise: `+`, `-`, `*`, `/`, `**`
2. ✅ Statistics: `mean()`, `std()`, `var()`, `min()`, `max()`
3. ✅ Aggregations work on entire array or along axis

### Filtering:
1. ✅ Boolean indexing: `arr[arr > 5]`
2. ✅ Multiple conditions: `&` (AND), `|` (OR), `~` (NOT)
3. ✅ `np.where()` for conditional replacement

### Sorting:
1. ✅ `np.sort()` - Returns sorted array
2. ✅ `np.argsort()` - Returns sorting indices
3. ✅ `np.unique()` - Find unique values

### Random:
1. ✅ `rand()` - Uniform [0, 1)
2. ✅ `randn()` - Normal distribution
3. ✅ `randint()` - Random integers
4. ✅ `seed()` - For reproducibility

